### ISSUE TITLE
Npm auth is "required" but also isn't

### ISSUE THREAD

**Issue by zramsay** [cerc-io/stack-orchestrator#103]
ran into this error then tried `export CERC_NPM_AUTH_TOKEN="whatever"` and that unblocked me

```
root@ubuntu-s-4vcpu-8gb-tor1-01:~# ./laconic-so build-containers
dir is: /root/.shiv/laconic-so_b7fd3e11c5bf3e1f9b1416bc9c67c93ee903d6b91b02bd68384eddff7d929cd7/site-packages/app/data/container-build
Dev Root is: /root/cerc
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/./laconic-so/__main__.py", line 3, in <module>
  File "/root/./laconic-so/_bootstrap/__init__.py", line 247, in bootstrap
  File "/root/./laconic-so/_bootstrap/__init__.py", line 38, in run
  File "/root/.shiv/laconic-so_b7fd3e11c5bf3e1f9b1416bc9c67c93ee903d6b91b02bd68384eddff7d929cd7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.shiv/laconic-so_b7fd3e11c5bf3e1f9b1416bc9c67c93ee903d6b91b02bd68384eddff7d929cd7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.shiv/laconic-so_b7fd3e11c5bf3e1f9b1416bc9c67c93ee903d6b91b02bd68384eddff7d929cd7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.shiv/laconic-so_b7fd3e11c5bf3e1f9b1416bc9c67c93ee903d6b91b02bd68384eddff7d929cd7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.shiv/laconic-so_b7fd3e11c5bf3e1f9b1416bc9c67c93ee903d6b91b02bd68384eddff7d929cd7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.shiv/laconic-so_b7fd3e11c5bf3e1f9b1416bc9c67c93ee903d6b91b02bd68384eddff7d929cd7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.shiv/laconic-so_b7fd3e11c5bf3e1f9b1416bc9c67c93ee903d6b91b02bd68384eddff7d929cd7/site-packages/app/build_containers.py", line 74, in command
    "CERC_NPM_AUTH_TOKEN": os.environ["CERC_NPM_AUTH_TOKEN"],
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'CERC_NPM_AUTH_TOKEN'
root@ubuntu-s-4vcpu-8gb-tor1-01:~# export CERC_NPM_AUTH_TOKEN="whatever"
root@ubuntu-s-4vcpu-8gb-tor1-01:~# ./laconic-so build-containers
dir is: /root/.shiv/laconic-so_b7fd3e11c5bf3e1f9b1416bc9c67c93ee903d6b91b02bd68384eddff7d929cd7/site-packages/app/data/container-build
Dev Root is: /root/cerc
Building: cerc/test-contract
```

**Comment by dboreham** [comment]
Should be fixed in: https://github.com/cerc-io/stack-orchestrator/pull/105

**Comment by dboreham** [comment]
Fix is in: https://github.com/cerc-io/stack-orchestrator/releases/tag/v1.0.5-alpha
