### ISSUE TITLE
Developer mode is broken

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#115]
Something added in the recent shiv changes seems to have broken developer mode installation in a clean machine:

```
$ laconic-so setup-repositories --git-ssh --pull
Dev Root is: /home/david/cerc
Traceback (most recent call last):
  File "/home/david/.local/bin/laconic-so", line 11, in <module>
    load_entry_point('laconic-stack-orchestrator', 'console_scripts', 'laconic-so')()
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/david/projects/cerc/stack-orchestrator/app/setup_repositories.py", line 96, in command
    with importlib.resources.open_text(data, "repository-list.txt") as repository_list_file:
AttributeError: module 'importlib' has no attribute 'resources'
```

**Comment by dboreham** [comment]
Fixed in: https://github.com/cerc-io/stack-orchestrator/pull/116
