### ISSUE TITLE
Error gracefully on missing stack

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#132]
If the user specifies a stack that doesn't exist, we throw an exception:

```
$ laconic-so --stack foo setup-repositories
Dev Root is: /home/david/cerc-test
Traceback (most recent call last):
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/bin/laconic-so", line 33, in <module>
    sys.exit(load_entry_point('laconic-stack-orchestrator', 'console_scripts', 'laconic-so')())
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/david/projects/vulcanize/stack-orchestrator/app/setup_repositories.py", line 109, in command
    stack_config = yaml.safe_load(open(stack_file_path, "r"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/david/projects/vulcanize/stack-orchestrator/app/data/stacks/foo/stack.yml'
```

**Comment by dboreham** [comment]
Fixed in: https://github.com/cerc-io/stack-orchestrator/pull/137
