### ISSUE TITLE
Exception thrown on docker command error

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#134]
Currently if a command returns error exit status from docker, we throw an exception like this:

```
$ laconic-so --stack fixturenet-laconicd build-npms --include laconic-registry-cli
Dev Root is: /home/david/cerc-test
Building npm package: laconic-registry-cli
Fixing up dependencies
Fixing up package @cerc-io/laconic-sdk
FATAL: Target package version (@cerc-io/laconic-sdk@0.1.4) not found
Traceback (most recent call last):
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/bin/laconic-so", line 33, in <module>
    sys.exit(load_entry_point('laconic-stack-orchestrator', 'console_scripts', 'laconic-so')())
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/david/projects/vulcanize/stack-orchestrator/app/build_npms.py", line 104, in command
    build_package(package)
  File "/home/david/projects/vulcanize/stack-orchestrator/app/build_npms.py", line 87, in build_package
    build_result = docker.run("cerc/builder-js",
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/python_on_whales/components/container/cli_wrapper.py", line 1537, in run
    return run(full_cmd, tty=tty, capture_stderr=False)
  File "/home/david/projects/vulcanize/stack-orchestrator/venv/lib/python3.9/site-packages/python_on_whales/utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker container run --add-host gitea.local:host-gateway --env CERC_NPM_AUTH_TOKEN=daa6901742b28100d0e901103db63f45f8688141 --interactive --tty --rm --user 1000:1000 --volume /home/david/cerc-test/laconic-registry-cli:/workspace cerc/builder-js sh -c cd /workspace && build-npm-package-local-dependencies.sh http://gitea.local:3000/api/packages/cerc-io/npm/`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr can be found above the stacktrace (it wasn't captured).
```

**Comment by dboreham** [comment]
Fixed in: https://github.com/cerc-io/stack-orchestrator/pull/136
