### ISSUE TITLE
Error thrown on using `laconic-so deploy-system`

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/stack-orchestrator#212]
Encountered error while following stack-orchestrator's [usage](https://github.com/cerc-io/stack-orchestrator#usage).

## Steps to reproduce:

```bash
$ laconic-so --verbose setup-repositories --include cerc-io/go-ethereum,cerc-io/ipld-eth-db,cerc-io/ipld-eth-server
```
```bash
$ laconic-so --verbose build-containers --include cerc/go-ethereum,cerc/go-ethereum-foundry,cerc/ipld-eth-db,cerc/ipld-eth-server
```
```bash
$ laconic-so --verbose deploy-system --include ipld-eth-db,go-ethereum-foundry,ipld-eth-server up
```

Traceback

```
Traceback (most recent call last):
  File "/home/dfqm8/.local/bin/laconic-so", line 33, in <module>
    sys.exit(load_entry_point('laconic-stack-orchestrator', 'console_scripts', 'laconic-so')())
  File "/home/dfqm8/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dfqm8/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dfqm8/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dfqm8/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dfqm8/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dfqm8/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/media/dfqm8/DATA1/work/work/stack-orchestrator/app/deploy_system.py", line 51, in command
    cluster_context = _make_cluster_context(ctx.obj, include, exclude, cluster)
  File "/media/dfqm8/DATA1/work/work/stack-orchestrator/app/deploy_system.py", line 226, in _make_cluster_context
    cluster_config = stack_config['config'] if 'config' in stack_config else None
UnboundLocalError: local variable 'stack_config' referenced before assignment
```

**Comment by dboreham** [comment]
Code path for non-stack case (which the doc really shouldn't reference now) is broken.
