### ISSUE TITLE
Wait for data availability on cluster config

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#219]
If the export command is executed prior to its data being available, we fail instead of re-trying. e.g.:

```
Traceback (most recent call last):
  File "/home/david/projects/stack-orchestrator/venv/bin/laconic-so", line 33, in <module>
    sys.exit(load_entry_point('laconic-stack-orchestrator', 'console_scripts', 'laconic-so')())
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/david/projects/stack-orchestrator/app/deploy_system.py", line 71, in command
    _orchestrate_cluster_config(ctx.obj, cluster_context.config, docker, container_exec_env)
  File "/home/david/projects/stack-orchestrator/app/deploy_system.py", line 297, in _orchestrate_cluster_config
    source_value = docker.compose.execute(pd.source_container,
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/python_on_whales/components/compose/cli_wrapper.py", line 203, in execute
    return run(full_cmd)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/python_on_whales/utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker compose --file /home/david/projects/stack-orchestrator/app/data/compose/docker-compose-fixturenet-laconicd.yml --project-name laconic-1c5ae848715b594e7f13e0ad47bdd792 exec --env CERC_HOST_UID=10014 --env CERC_HOST_GID=10014 --index 1 --no-TTY laconicd sh -c sh /docker-entrypoint-scripts.d/export-mykey.sh`.
It returned with code 1
The content of stdout is ''
The content of stderr is 'Error: mykey.info: key not found
Usage:
  laconicd keys export <name> [flags]
```

**Comment by dboreham** [comment]
Workaround is to run `deploy-system up` twice.
