### ISSUE TITLE
Pass private key from `laconicd` container using config option in `stack.yml`

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/stack-orchestrator#244]
The genesis account private key from [`laconicd`](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.32/app/data/compose/docker-compose-mobymask-laconicd.yml#L4) needs to be used in [`mobymask`](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.32/app/data/compose/docker-compose-watcher-mobymask-v2.yml#L24) container to deploy the MobyMask contract. The deployed contract addrress is then used in [`mobymask-app`](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.32/app/data/compose/docker-compose-watcher-mobymask-v2.yml#L79) container to deploy the web-app.
The private key of a secondary account also needs to be used in [`mobymask-watcher-server`](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.32/app/data/compose/docker-compose-watcher-mobymask-v2.yml#L44) container for the peer that would be sending txs to L2 chain.
    
Tried using the config option in `stack.yml` file as seen in [fixturenet-laconicd stack](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.32/app/data/stacks/fixturenet-laconicd/stack.yml).
* Expected: The private key passed is available when the service starts and command is run for deploying contract
* Actual: The private key passed from `laconicd` was not available in `mobymask` when the container starts.
    
Workaround:
* Started the `laconicd` container first in a separate compose file. 
* Performed [manual steps](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.32/app/data/stacks/mobymask-v2/README.md?plain=1#L62) to set account private keys for other containers.
* Had to configure a shared network between the [laconicd](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.32/app/data/compose/docker-compose-mobymask-laconicd.yml#L22) and [watcher](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.32/app/data/compose/docker-compose-watcher-mobymask-v2.yml#L124) compose files.

**Comment by dboreham** [comment]
I think this is a dup of: https://github.com/cerc-io/stack-orchestrator/issues/219

**Comment by dboreham** [comment]
#219 is fixed now, can we try to do this with the stack config mechanism?

**Comment by nikugogoi** [comment]
Tried using the stack config mechanism (https://github.com/cerc-io/stack-orchestrator/pull/258)
Getting an error when `mobymask` container is starting
```
$ laconic-so --stack mobymask-v2 deploy-system logs mobymask
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | > mobymask-server@1.0.0 start
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | > ts-node index.ts
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | This version of µWS is not compatible with your Node.js build:
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | Error: node-loader:
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/ganache/dist/node/3hfvwJad.node)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | Falling back to a NodeJS implementation; performance may be degraded.
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | Error: Cannot find module './secrets.json'
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | Require stack:
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | - /app/packages/server/index.ts
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Module.require (node:internal/modules/cjs/loader:1028:19)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at require (node:internal/modules/cjs/helpers:102:18)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Object.<anonymous> (/app/packages/server/index.ts:28:62)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Module._compile (node:internal/modules/cjs/loader:1126:14)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1597:23)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1600:12) {
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |   code: 'MODULE_NOT_FOUND',
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |   requireStack: [ '/app/packages/server/index.ts' ]
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | }
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | npm ERR! Lifecycle script `start` failed with error: 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | npm ERR! Error: command failed 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | npm ERR!   in workspace: mobymask-server@1.0.0 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | npm ERR!   at location: /app/packages/server 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |
```
It seems the `import-key.sh` is not executed before the container starts and so `secrets.json` file is not present

**Comment by dboreham** [comment]
This is "as-designed" : having a start order dependency imposed on a set of containers in a cluster will typically prove problematic so we don't do that. The solution would be to start the container, but not start the service process therein until the dependent variable is available. Or make the service process tolerate starting without its config.

**Comment by dboreham** [comment]
Closing as wontfix.
