### ISSUE TITLE
Error thrown in building `cerc/go-ethereum-foundry` container used in erc20 watcher stack

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/stack-orchestrator#246]
On following steps in [erc20 watcher stack](https://github.com/cerc-io/stack-orchestrator/tree/v1.0.32/app/data/stacks/erc20):
* Expected: Complete successfully without errors
* Actual:
  * Got error in `cerc/go-ethereum-foundry` container build for missing `cerc/foundry` image
  * This is expected as `cerc/foundry` has not been added to erc20 watcher [stack.yml](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.32/app/data/stacks/erc20/stack.yml)
  * After adding cerc/foundry to stack, error is thrown again in `cerc/go-ethereum-foundry` container build
      ```
      Step 2/14 : RUN apk update ; apk add --no-cache --allow-untrusted ca-certificates curl bash git jq
       ---> Running in 50ce263b017c
      /bin/sh: 1: apk: not found
      /bin/sh: 1: apk: not found
      The command '/bin/sh -c apk update ; apk add --no-cache --allow-untrusted ca-certificates curl bash git jq' returned a non-zero code: 127
      Error running build for cerc/go-ethereum-foundry
      FATAL Error: container build failed and --continue-on-error not set, exiting
      ```

**Comment by zramsay** [comment]
related to #215, looks like things broke a bit more since then

**Comment by dboreham** [comment]
> related to #215, looks like things broke a bit more since then

Related how?

**Comment by dboreham** [comment]
I think this must be somehow related to the environment because the container builds fine for me.

This seems odd:

```
/bin/sh: 1: apk: not found
/bin/sh: 1: apk: not found
```

`apk` is an Alipine thing, but we now build a Debian container.

It's like it is somehow using this Dockerfile: https://github.com/dboreham/foundry/blob/cerc-release/Dockerfile#L9
and not this one: https://github.com/dboreham/foundry/blob/cerc-release/Dockerfile-debian#L44

**Comment by dboreham** [comment]
Oh wait, this error is from building `go-ethereum-foundry`.
Almost certainly that's because the container expects an Alpine base.

**Comment by nikugogoi** [comment]
Tried using the stack config mechanism (https://github.com/cerc-io/stack-orchestrator/pull/258)
Getting an error when `mobymask` container is starting
```
$ laconic-so --stack mobymask-v2 deploy-system logs mobymask
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | > mobymask-server@1.0.0 start
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | > ts-node index.ts
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | This version of µWS is not compatible with your Node.js build:
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | Error: node-loader:
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/ganache/dist/node/3hfvwJad.node)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | Falling back to a NodeJS implementation; performance may be degraded.
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | Error: Cannot find module './secrets.json'
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | Require stack:
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | - /app/packages/server/index.ts
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Module.require (node:internal/modules/cjs/loader:1028:19)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at require (node:internal/modules/cjs/helpers:102:18)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Object.<anonymous> (/app/packages/server/index.ts:28:62)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Module._compile (node:internal/modules/cjs/loader:1126:14)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1597:23)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |     at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1600:12) {
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |   code: 'MODULE_NOT_FOUND',
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |   requireStack: [ '/app/packages/server/index.ts' ]
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | }
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | npm ERR! Lifecycle script `start` failed with error: 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | npm ERR! Error: command failed 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | npm ERR!   in workspace: mobymask-server@1.0.0 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  | npm ERR!   at location: /app/packages/server 
laconic-aeb84676de2b0a7671ae90d537fc7d26-mobymask-1  |
```
It seems the `import-key.sh` is not executed before the container starts and so `secrets.json` file is not present

**Comment by nikugogoi** [comment]
Followed the steps in [erc20 watcher stack](https://github.com/cerc-io/stack-orchestrator/tree/v1.0.35/app/data/stacks/erc20#readme) after clearing out all docker images and build cache. Also cleared out local repositories in cerc directory.
```bash
# Clear all images
docker rmi $(docker images -aq)

# Clear volumes
docker volume prune

# Clear build cache
docker system prune

# Clear local repositories
rm -rf ~/cerc/
```

In the [setup steps](https://github.com/cerc-io/stack-orchestrator/tree/v1.0.35/app/data/stacks/erc20#setup) we face issue after running `deploy-system up` command. On checking health using `docker ps`, the `go-ethereum-foundry` container is not healthy.

NOTE: In `build-containers` step there should be an error for `cerc/foundry` image not found.
The fix is to include `cerc/foundry` container and `dboreham/foundry` repo in erc20 watcher [stack.yml](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.35/app/data/stacks/erc20/stack.yml)
But we get around this by running the following:
```
laconic-so setup-repositories --include dboreham/foundry

laconic-so build-containers --include cerc/foundry
```

In container logs we see the following:
```
Geth started
Geth PID: 64
Curling: http://0.0.0.0:8545/
--datadir /root/ethereum --networkid 99 --port=38545 --mine --miner.threads=1 --allow-insecure-unlock --http --http.api admin,debug,eth,miner,net,personal,txpool,web3,statediff --http.corsdomain * --http.vhosts * --nodiscover --http.addr=0.0.0.0 --http.port=8545 --syncmode=full --gcmode=archive --statediff --statediff.db.host=ipld-eth-db --statediff.db.port=5432 --statediff.db.user=vdbm --statediff.db.password=password --statediff.db.name=cerc_testing --statediff.db.nodeid 1 --statediff.db.clientname test1 --statediff.writing=true --statediff.db.type=postgres --statediff.db.driver=sqlx --ws --ws.addr=0.0.0.0 --ws.origins * --ws.api=admin,debug,eth,miner,net,personal,txpool,web3 --nat=none --miner.gasprice 16000000000 --nat=none --unlock=0xB2fcBbb669f3dEeF689a6A94eA6D843149C266F7 --password=/root/ethereum/config/password --metrics --metrics.expensive --metrics.addr 0.0.0.0 --metrics.port 6060
testnet:  Account: 0xB2fcBbb669f3dEeF689a6A94eA6D843149C266F7 (default)
Curling: http://0.0.0.0:8545/ complete
Geth Start up completed!
Fatal: Failed to start mining: etherbase missing: etherbase must be explicitly specified
++ nc -vz localhost 8545
nc: connect to localhost (127.0.0.1) port 8545 (tcp) failed: Connection refused
nc: connect to localhost (::1) port 8545 (tcp) failed: Cannot assign requested address
```
This issue should have been resolved as mentioned in https://github.com/cerc-io/stack-orchestrator/issues/215.
But facing it still after clearing out images and repositories.

**Comment by nikugogoi** [comment]
Followed the steps in [erc20 watcher stack](https://github.com/cerc-io/stack-orchestrator/tree/v1.0.35/app/data/stacks/erc20#readme) after clearing out all docker images and build cache. Also cleared out local repositories in cerc directory.
```bash
# Clear all images
docker rmi $(docker images -aq)

# Clear volumes
docker volume prune

# Clear build cache
docker system prune

# Clear local repositories
rm -rf ~/cerc/
```

In the [setup steps](https://github.com/cerc-io/stack-orchestrator/tree/v1.0.35/app/data/stacks/erc20#setup) we face issue after running `deploy-system up` command. On checking health using `docker ps`, the `go-ethereum-foundry` container is not healthy.

NOTE: In `build-containers` step there should be an error for `cerc/foundry` image not found.
The fix is to include `cerc/foundry` container and `dboreham/foundry` repo in erc20 watcher [stack.yml](https://github.com/cerc-io/stack-orchestrator/blob/v1.0.35/app/data/stacks/erc20/stack.yml)
But we get around this by running the following:
```
laconic-so setup-repositories --include dboreham/foundry

laconic-so build-containers --include cerc/foundry
```

In container logs we see the following:
```
Geth started
Geth PID: 64
Curling: http://0.0.0.0:8545/
--datadir /root/ethereum --networkid 99 --port=38545 --mine --miner.threads=1 --allow-insecure-unlock --http --http.api admin,debug,eth,miner,net,personal,txpool,web3,statediff --http.corsdomain * --http.vhosts * --nodiscover --http.addr=0.0.0.0 --http.port=8545 --syncmode=full --gcmode=archive --statediff --statediff.db.host=ipld-eth-db --statediff.db.port=5432 --statediff.db.user=vdbm --statediff.db.password=password --statediff.db.name=cerc_testing --statediff.db.nodeid 1 --statediff.db.clientname test1 --statediff.writing=true --statediff.db.type=postgres --statediff.db.driver=sqlx --ws --ws.addr=0.0.0.0 --ws.origins * --ws.api=admin,debug,eth,miner,net,personal,txpool,web3 --nat=none --miner.gasprice 16000000000 --nat=none --unlock=0xB2fcBbb669f3dEeF689a6A94eA6D843149C266F7 --password=/root/ethereum/config/password --metrics --metrics.expensive --metrics.addr 0.0.0.0 --metrics.port 6060
testnet:  Account: 0xB2fcBbb669f3dEeF689a6A94eA6D843149C266F7 (default)
Curling: http://0.0.0.0:8545/ complete
Geth Start up completed!
Fatal: Failed to start mining: etherbase missing: etherbase must be explicitly specified
++ nc -vz localhost 8545
nc: connect to localhost (127.0.0.1) port 8545 (tcp) failed: Connection refused
nc: connect to localhost (::1) port 8545 (tcp) failed: Cannot assign requested address
```
This issue should have been resolved as mentioned in https://github.com/cerc-io/stack-orchestrator/issues/215.
But facing it still after clearing out images and repositories.

**Comment by dboreham** [comment]
I think that's a different issue. This one is about _building_ the container. Error above is about a runtime error. I'll find the issue relating to the runtime error and move the comment there.
