### ISSUE TITLE
L2 (Optimism) deployment crashed

### ISSUE THREAD

**Issue by prathamesh0** [cerc-io/stack-orchestrator#361]
We have L1 and L2 deployed separately using [fixturenet-eth](https://github.com/cerc-io/stack-orchestrator/tree/main/app/data/stacks/fixturenet-eth) and [fixturenet-optimism l2-only](https://github.com/cerc-io/stack-orchestrator/blob/main/app/data/stacks/fixturenet-optimism/l2-only.md) on the same VM.
While L1 deployment seems to be running fine, it seems that the L2 deployment has stopped working. It has been up for 42 hours with the `op-batcher` container crashed at `~27th` hour.

Relevant logs:
```bash
l2-geth:

INFO [04-20|16:34:18.955] Chain head was updated                   number=49239 hash=262063..b018fb root=72c28d..b912ac elapsed="138.072µs"
INFO [04-20|16:34:19.005] Starting work on payload                 id=0x62c3817207a8b800
INFO [04-20|16:34:19.005] Updated payload                          id=0x62c3817207a8b800 number=49240 hash=e3572b..db6615 txs=1 gas=47641     fees=0            root=0c8c36..258d30 elapsed="382.177µs"
INFO [04-20|16:34:20.951] Stopping work on payload                 id=0x62c3817207a8b800 reason=delivery
INFO [04-20|16:34:20.953] Imported new potential chain segment     number=49240 hash=e3572b..db6615 blocks=1 txs=1 mgas=0.048 elapsed=1.049ms     mgasps=45.383   dirty=505.53KiB
INFO [04-20|16:34:20.955] Chain head was updated                   number=49240 hash=e3572b..db6615 root=0c8c36..258d30 elapsed="260.618µs"
INFO [04-20|16:34:30.739] Regenerating historical state            block=1 target=49107 remaining=49106 elapsed="1.11µs"
INFO [04-20|16:34:38.739] Regenerating historical state            block=40113 target=49107 remaining=8994  elapsed=8.000126517s
INFO [04-20|16:34:40.517] Historical state regenerated             block=49107 elapsed=9.777951736s nodes=20.04KiB preimages=0.00B
INFO [04-20|16:34:40.518] Starting work on payload                 id=0xbbde9752e32d3c53
WARN [04-20|16:34:40.521] State not available, ignoring new payload 
INFO [04-20|16:34:41.429] Regenerating historical state            block=1     target=49107 remaining=49106 elapsed="1.095µs"
WARN [04-20|16:34:41.525] State not available, ignoring new payload 
WARN [04-20|16:34:42.528] State not available, ignoring new payload 
WARN [04-20|16:34:43.531] State not available, ignoring new payload 
WARN [04-20|16:34:44.534] State not available, ignoring new payload 
WARN [04-20|16:34:45.537] State not available, ignoring new payload 
WARN [04-20|16:34:46.541] State not available, ignoring new payload 
WARN [04-20|16:34:47.544] State not available, ignoring new payload 
WARN [04-20|16:34:48.547] State not available, ignoring new payload 
INFO [04-20|16:34:49.429] Regenerating historical state            block=39205 target=49107 remaining=9902  elapsed=8.000224644s
WARN [04-20|16:34:49.550] State not available, ignoring new payload 
WARN [04-20|16:34:50.553] State not available, ignoring new payload 
INFO [04-20|16:34:51.488] Historical state regenerated             block=49107 elapsed=10.059030205s nodes=20.04KiB preimages=0.00B
INFO [04-20|16:34:51.488] Stopping work on payload                 id=0xbbde9752e32d3c53 reason=delivery
WARN [04-20|16:34:51.556] State not available, ignoring new payload 
WARN [04-20|16:34:52.559] State not available, ignoring new payload 

op-node:

t=2023-04-21T07:05:54+0000 lvl=warn msg="avoiding sequencing to not interrupt safe-head changes" onto=0x5716da65f3e1eff7b1eaac74b505fb504ee2b6edef4427f7d6b3a3ac476f1425:49107 onto_time=1,682,008,195
t=2023-04-21T07:05:54+0000 lvl=warn msg="delaying sequencing to not interrupt safe-head changes" onto=0x5716da65f3e1eff7b1eaac74b505fb504ee2b6edef4427f7d6b3a3ac476f1425:49107 onto_time=1,682,008,195
t=2023-04-21T07:05:55+0000 lvl=warn msg="did not finish previous block building, starting new building now" prev_onto=0x5716da65f3e1eff7b1eaac74b505fb504ee2b6edef4427f7d6b3a3ac476f1425:49107 prev_payload_id=0xd80a40ead2268053 new_onto=0x5716da65f3e1eff7b1eaac74b505fb504ee2b6edef4427f7d6b3a3ac476f1425:49107
t=2023-04-21T07:05:55+0000 lvl=warn msg="Derivation process temporary error"     attempts=3108 err="engine stage failed: temp: temporarily cannot insert new safe block: failed to complete building on top of L2 chain 0x5716da65f3e1eff7b1eaac74b505fb504ee2b6edef4427f7d6b3a3ac476f1425:49107, id: 0xd80a40ead2268053, error (1): execution payload cannot be validated yet, latest valid hash is <nil>"
t=2023-04-21T07:05:56+0000 lvl=warn msg="avoiding sequencing to not interrupt safe-head changes" onto=0x5716da65f3e1eff7b1eaac74b505fb504ee2b6edef4427f7d6b3a3ac476f1425:49107 onto_time=1,682,008,195
t=2023-04-21T07:05:56+0000 lvl=warn msg="delaying sequencing to not interrupt safe-head changes" onto=0x5716da65f3e1eff7b1eaac74b505fb504ee2b6edef4427f7d6b3a3ac476f1425:49107 onto_time=1,682,008,195

op-batcher:

t=2023-04-20T16:34:23+0000 lvl=info msg="Created channel"                    id=62f62a89d07d38a9a426e5ad67276265 l1Head=0x2094c96104fb73710497af6d4e555db77ad51d58f297b31dafed4dbe795bfb2f:32745 blocks_pending=14
t=2023-04-20T16:34:31+0000 lvl=warn msg="Error calculating L2 block range"   err="failed to get sync status: Post \"http://op-node:8547\": context deadline exceeded"
t=2023-04-20T16:34:33+0000 lvl=warn msg="Error calculating L2 block range"   err="failed to get sync status: Post \"http://op-node:8547\": context deadline exceeded"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8421f8]

goroutine 40 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0?)
        /go/pkg/mod/github.com/ethereum-optimism/op-geth@v1.11.2-de8c5df46.0.20230324105532-555b76f39878/core/types/block.go:429 +0x38
github.com/ethereum-optimism/optimism/op-node/rollup/derive.L2BlockToBlockRef({0x12c0f00, 0x0}, 0xc000305180)
        /app/op-node/rollup/derive/l2block_util.go:29 +0x65
github.com/ethereum-optimism/optimism/op-batcher/batcher.(*BatchSubmitter).loadBlocksIntoState(0xc0002f8000, {0x12bf810, 0xc00032d300})
        /app/op-batcher/batcher/driver.go:216 +0x485
github.com/ethereum-optimism/optimism/op-batcher/batcher.(*BatchSubmitter).loop(0xc0002f8000)
        /app/op-batcher/batcher/driver.go:293 +0xc5
created by github.com/ethereum-optimism/optimism/op-batcher/batcher.(*BatchSubmitter).Start
        /app/op-batcher/batcher/driver.go:144 +0x205
```

**Comment by prathamesh0** [comment]
Haven't faced the above errors again; we've also moved on to use a stable Optimism release since then.
