### ISSUE TITLE
`fixturenet-eth-geth` build-containers fails (ran via the optimism stack, also fails in the pokt stack)

### ISSUE THREAD

**Issue by zramsay** [cerc-io/stack-orchestrator#395]
```
Step 14/17 : RUN cd /opt/testnet && make genesis-el
 ---> Running in 1dc8d7427c61
cd el; ./build_el.sh
Traceback (most recent call last):
  File "/apps/el-gen/genesis_geth.py", line 1, in <module>
    from web3.auto import w3
  File "/usr/lib/python3.11/site-packages/web3/__init__.py", line 6, in <module>
    from eth_account import (
  File "/usr/lib/python3.11/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (
  File "/usr/lib/python3.11/site-packages/eth_account/account.py", line 59, in <module>
    from eth_account.messages import (
  File "/usr/lib/python3.11/site-packages/eth_account/messages.py", line 26, in <module>
    from eth_account._utils.structured_data.hashing import (
  File "/usr/lib/python3.11/site-packages/eth_account/_utils/structured_data/hashing.py", line 9, in <module>
    from eth_abi import (
  File "/usr/lib/python3.11/site-packages/eth_abi/__init__.py", line 6, in <module>
    from eth_abi.abi import (  # NOQA
  File "/usr/lib/python3.11/site-packages/eth_abi/abi.py", line 1, in <module>
    from eth_abi.codec import (
  File "/usr/lib/python3.11/site-packages/eth_abi/codec.py", line 16, in <module>
    from eth_abi.decoding import (
  File "/usr/lib/python3.11/site-packages/eth_abi/decoding.py", line 14, in <module>
    from eth_abi.base import (
  File "/usr/lib/python3.11/site-packages/eth_abi/base.py", line 7, in <module>
    from .grammar import (
  File "/usr/lib/python3.11/site-packages/eth_abi/grammar.py", line 4, in <module>
    import parsimonious
  File "/usr/lib/python3.11/site-packages/parsimonious/__init__.py", line 9, in <module>
    from parsimonious.grammar import Grammar, TokenGrammar
  File "/usr/lib/python3.11/site-packages/parsimonious/grammar.py", line 14, in <module>
    from parsimonious.expressions import (Literal, Regex, Sequence, OneOf,
  File "/usr/lib/python3.11/site-packages/parsimonious/expressions.py", line 9, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
Traceback (most recent call last):
  File "/opt/testnet/el/../accounts/mnemonic_to_csv.py", line 1, in <module>
    from web3.auto import w3
  File "/usr/lib/python3.11/site-packages/web3/__init__.py", line 6, in <module>
    from eth_account import (
  File "/usr/lib/python3.11/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (
  File "/usr/lib/python3.11/site-packages/eth_account/account.py", line 59, in <module>
    from eth_account.messages import (
  File "/usr/lib/python3.11/site-packages/eth_account/messages.py", line 26, in <module>
    from eth_account._utils.structured_data.hashing import (
  File "/usr/lib/python3.11/site-packages/eth_account/_utils/structured_data/hashing.py", line 9, in <module>
    from eth_abi import (
  File "/usr/lib/python3.11/site-packages/eth_abi/__init__.py", line 6, in <module>
    from eth_abi.abi import (  # NOQA
  File "/usr/lib/python3.11/site-packages/eth_abi/abi.py", line 1, in <module>
    from eth_abi.codec import (
  File "/usr/lib/python3.11/site-packages/eth_abi/codec.py", line 16, in <module>
    from eth_abi.decoding import (
  File "/usr/lib/python3.11/site-packages/eth_abi/decoding.py", line 14, in <module>
    from eth_abi.base import (
  File "/usr/lib/python3.11/site-packages/eth_abi/base.py", line 7, in <module>
    from .grammar import (
  File "/usr/lib/python3.11/site-packages/eth_abi/grammar.py", line 4, in <module>
    import parsimonious
  File "/usr/lib/python3.11/site-packages/parsimonious/__init__.py", line 9, in <module>
    from parsimonious.grammar import Grammar, TokenGrammar
  File "/usr/lib/python3.11/site-packages/parsimonious/grammar.py", line 14, in <module>
    from parsimonious.expressions import (Literal, Regex, Sequence, OneOf,
  File "/usr/lib/python3.11/site-packages/parsimonious/expressions.py", line 9, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
make: *** [Makefile:9: genesis-el] Error 1
The command '/bin/sh -c cd /opt/testnet && make genesis-el' returned a non-zero code: 2
Dev Root is: /root/cerc
Building: cerc/go-ethereum
Building: cerc/lighthouse
Building: cerc/fixturenet-eth-geth
Error running build for cerc/fixturenet-eth-geth
FATAL Error: container build failed and --continue-on-error not set, exiting
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_SCRIPT_DEBUG\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_ADDRESS\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_PRIV_KEY\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_ADDRESS_2\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_PRIV_KEY_2\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_SCRIPT_DEBUG\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_CHAIN_ID\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_RPC\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_ACCOUNTS_CSV_URL\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_RPC\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_SCRIPT_DEBUG\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_RPC\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_SCRIPT_DEBUG\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_SCRIPT_DEBUG\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_RPC\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_SCRIPT_DEBUG\" variable is not set. Defaulting to a blank string."
time="2023-05-17T21:03:40Z" level=warning msg="The \"CERC_L1_RPC\" variable is not set. Defaulting to a blank string."
 op-proposer Pulling 
 fixturenet-eth-lighthouse-2 Pulling 
 fixturenet-eth-bootnode-geth Pulling 
 fixturenet-eth-geth-1 Pulling 
 op-geth Pulling 
 fixturenet-eth-bootnode-lighthouse Pulling 
 op-node-l2-config-gen Pulling 
 op-node Pulling 
 op-batcher Pulling 
 fixturenet-eth-lighthouse-1 Pulling 
 fixturenet-eth-geth-2 Pulling 
 fixturenet-optimism-contracts Pulling 
 op-node-l2-config-gen Error 
 op-node Error 
 fixturenet-eth-geth-2 Error 
 fixturenet-eth-bootnode-lighthouse Error 
 op-geth Error 
 fixturenet-eth-lighthouse-2 Error 
 fixturenet-eth-geth-1 Error 
 fixturenet-eth-lighthouse-1 Error 
 op-proposer Error 
 fixturenet-eth-bootnode-geth Error 
 op-batcher Error 
 fixturenet-optimism-contracts Error 
Error response from daemon: pull access denied for cerc/optimism-op-node, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/laconic-so/__main__.py", line 3, in <module>
  File "/usr/local/bin/laconic-so/_bootstrap/__init__.py", line 253, in bootstrap
  File "/usr/local/bin/laconic-so/_bootstrap/__init__.py", line 38, in run
  File "/root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/app/deploy_system.py", line 68, in command
    docker.compose.up(detach=True, services=extra_args_list)
  File "/root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/python_on_whales/components/compose/cli_wrapper.py", line 737, in up
    run(full_cmd, capture_stdout=quiet, capture_stderr=quiet)
  File "/root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/python_on_whales/utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker compose --file /root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/app/data/compose/docker-compose-fixturenet-eth.yml --file /root/.shiv/laconic-so_96b3505d014cc2f8e7b3a32c5be5b10fafee7b0d0823032d7478ec30dc5c3b69/site-packages/app/data/compose/docker-compose-fixturenet-optimism.yml --project-name laconic-c8570c6fd85148f2a9093ce7f790c708 up --detach`.
It returned with code 18
The content of stdout can be found above the stacktrace (it wasn't captured).
```

**Comment by dboreham** [comment]
Hmm...I don't think our basic fixturenet stack should depend on anything optimism related at all.

**Comment by dboreham** [comment]
@zramsay post the command you're running please.

**Comment by zramsay** [comment]
```
laconic-so --stack fixturenet-pocket setup-repositories
laconic-so --stack fixturenet-pocket build-containers
laconic-so --stack fixturenet-pocket deploy up
```

```
laconic-so --stack fixturenet-optimism setup
laconic-so --stack fixturenet-optimism build-containers
laconic-so --stack fixturenet-optimism deploy up
```

**Comment by dboreham** [comment]
Which one fails?

**Comment by dboreham** [comment]
Um, I see 7 commands above. Which one was run to produce the original failed container build output?

**Comment by zramsay** [comment]
my bad, if I run:

```
laconic-so --stack fixturenet-optimism setup-repositories
cd ~/cerc/optimism && git checkout v1.0.4
laconic-so --stack fixturenet-optimism build-containers
```
then `build-containers` fails with the output shown at the beginning of this issue

If I run
```
laconic-so --stack fixturenet-pocket setup-repositories
laconic-so --stack fixturenet-pocket build-containers
```
then `build-containers` has the same error other than some stack specific fallout:

```
Step 14/17 : RUN cd /opt/testnet && make genesis-el
 ---> Running in 6544d8664499
cd el; ./build_el.sh
Traceback (most recent call last):
  File "/apps/el-gen/genesis_geth.py", line 1, in <module>
    from web3.auto import w3
  File "/usr/lib/python3.11/site-packages/web3/__init__.py", line 6, in <module>
    from eth_account import (
  File "/usr/lib/python3.11/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (
  File "/usr/lib/python3.11/site-packages/eth_account/account.py", line 59, in <module>
    from eth_account.messages import (
  File "/usr/lib/python3.11/site-packages/eth_account/messages.py", line 26, in <module>
    from eth_account._utils.structured_data.hashing import (
  File "/usr/lib/python3.11/site-packages/eth_account/_utils/structured_data/hashing.py", line 9, in <module>
    from eth_abi import (
  File "/usr/lib/python3.11/site-packages/eth_abi/__init__.py", line 6, in <module>
    from eth_abi.abi import (  # NOQA
  File "/usr/lib/python3.11/site-packages/eth_abi/abi.py", line 1, in <module>
    from eth_abi.codec import (
  File "/usr/lib/python3.11/site-packages/eth_abi/codec.py", line 16, in <module>
    from eth_abi.decoding import (
  File "/usr/lib/python3.11/site-packages/eth_abi/decoding.py", line 14, in <module>
    from eth_abi.base import (
  File "/usr/lib/python3.11/site-packages/eth_abi/base.py", line 7, in <module>
    from .grammar import (
  File "/usr/lib/python3.11/site-packages/eth_abi/grammar.py", line 4, in <module>
    import parsimonious
  File "/usr/lib/python3.11/site-packages/parsimonious/__init__.py", line 9, in <module>
    from parsimonious.grammar import Grammar, TokenGrammar
  File "/usr/lib/python3.11/site-packages/parsimonious/grammar.py", line 14, in <module>
    from parsimonious.expressions import (Literal, Regex, Sequence, OneOf,
  File "/usr/lib/python3.11/site-packages/parsimonious/expressions.py", line 9, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
Traceback (most recent call last):
  File "/opt/testnet/el/../accounts/mnemonic_to_csv.py", line 1, in <module>
    from web3.auto import w3
  File "/usr/lib/python3.11/site-packages/web3/__init__.py", line 6, in <module>
    from eth_account import (
  File "/usr/lib/python3.11/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (
  File "/usr/lib/python3.11/site-packages/eth_account/account.py", line 59, in <module>
    from eth_account.messages import (
  File "/usr/lib/python3.11/site-packages/eth_account/messages.py", line 26, in <module>
    from eth_account._utils.structured_data.hashing import (
  File "/usr/lib/python3.11/site-packages/eth_account/_utils/structured_data/hashing.py", line 9, in <module>
    from eth_abi import (
  File "/usr/lib/python3.11/site-packages/eth_abi/__init__.py", line 6, in <module>
    from eth_abi.abi import (  # NOQA
  File "/usr/lib/python3.11/site-packages/eth_abi/abi.py", line 1, in <module>
    from eth_abi.codec import (
  File "/usr/lib/python3.11/site-packages/eth_abi/codec.py", line 16, in <module>
    from eth_abi.decoding import (
  File "/usr/lib/python3.11/site-packages/eth_abi/decoding.py", line 14, in <module>
    from eth_abi.base import (
  File "/usr/lib/python3.11/site-packages/eth_abi/base.py", line 7, in <module>
    from .grammar import (
  File "/usr/lib/python3.11/site-packages/eth_abi/grammar.py", line 4, in <module>
    import parsimonious
  File "/usr/lib/python3.11/site-packages/parsimonious/__init__.py", line 9, in <module>
    from parsimonious.grammar import Grammar, TokenGrammar
  File "/usr/lib/python3.11/site-packages/parsimonious/grammar.py", line 14, in <module>
    from parsimonious.expressions import (Literal, Regex, Sequence, OneOf,
  File "/usr/lib/python3.11/site-packages/parsimonious/expressions.py", line 9, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
make: *** [Makefile:9: genesis-el] Error 1
The command '/bin/sh -c cd /opt/testnet && make genesis-el' returned a non-zero code: 2
Dev Root is: /root/cerc
Building: cerc/go-ethereum
Building: cerc/lighthouse
Building: cerc/fixturenet-eth-geth
Error running build for cerc/fixturenet-eth-geth
FATAL Error: container build failed and --continue-on-error not set, exiting
time="2023-05-18T14:56:41Z" level=warning msg="The \"CERC_SCRIPT_DEBUG\" variable is not set. Defaulting to a blank string."
 pocket Pulling 
 fixturenet-eth-geth-1 Pulling 
 fixturenet-eth-lighthouse-1 Pulling 
 fixturenet-eth-lighthouse-2 Pulling 
 fixturenet-eth-bootnode-lighthouse Pulling 
 fixturenet-eth-bootnode-geth Pulling 
 fixturenet-eth-geth-2 Pulling 
 pocket Error 
 fixturenet-eth-bootnode-geth Error 
 fixturenet-eth-lighthouse-2 Error 
 fixturenet-eth-lighthouse-1 Error 
 fixturenet-eth-geth-2 Error 
 fixturenet-eth-bootnode-lighthouse Error 
 fixturenet-eth-geth-1 Error 
Error response from daemon: pull access denied for cerc/pocket, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/laconic-so/__main__.py", line 3, in <module>
  File "/usr/local/bin/laconic-so/_bootstrap/__init__.py", line 253, in bootstrap
  File "/usr/local/bin/laconic-so/_bootstrap/__init__.py", line 38, in run
  File "/root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/app/deploy_system.py", line 68, in command
    docker.compose.up(detach=True, services=extra_args_list)
  File "/root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/python_on_whales/components/compose/cli_wrapper.py", line 737, in up
    run(full_cmd, capture_stdout=quiet, capture_stderr=quiet)
  File "/root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/python_on_whales/utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker compose --file /root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/app/data/compose/docker-compose-fixturenet-pocket.yml --file /root/.shiv/laconic-so_18f7dda7b790bd24144c15bf17df24abba47f2656e1cfe649ed47fd02e49b689/site-packages/app/data/compose/docker-compose-fixturenet-eth.yml --project-name laconic-014e67905811b672de83071bcfc60b19 up --detach`.
It returned with code 18
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr can be found above the stacktrace (it wasn't captured).
2023-05-18 14:56:42,050 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2023-05-18 14:56:42,050 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
```

**Comment by dboreham** [comment]
Ok sounds like the optimism container build is broken, affecting stacks that depend on that container (not including fixturenet-eth). I'll leave it to @prathamesh0 to investigate and resolve.

**Comment by dboreham** [comment]
Finally understand this bug. User ran two commands in a script or a shell, with stop on error disabled. The first one failed (due to [this bug](https://github.com/cerc-io/stack-orchestrator/issues/397)). The second one was then executed and failed because containers that the first command was supposed to build never got built.

Closing as a dup of https://github.com/cerc-io/stack-orchestrator/issues/397
