### ISSUE TITLE
fixturenet-optimism-contracts container fails to start

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#459]
Log output:

```
yarn run v1.22.19
$ /app/node_modules/.bin/hardhat send-balance --to 0x73e56be4eba6e314522f6d3458353abb3c936b1f --amount 2 --private-key 0x888814df89c4358d7ddb3fa4b0213e7331239a80e1f013eaa7b2deca2a41a218 --network getting-started
An unexpected error occurred:

Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":56,\"error\":{\"code\":-32000,\"message\":\"invalid transaction v, r, s values\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf86d80843b9aca008252089473e56be4eba6e314522f6d3458353abb3c936b1f881bc16d674ec800008082099ca0ef68433d7974e759456725dc8f582fdd022780a398752150cbba8164ae85fac7a069dc3fd4c2fb59e1db043451e34e40b0c3a57a9e0c2f892856b3de851d770cb9\"],\"id\":56,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://fixturenet-eth-geth-1:8545", code=SERVER_ERROR, version=web/5.7.0)
    at Logger.makeError (/app/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/app/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at /app/node_modules/@ethersproject/web/src.ts/index.ts:335:28
    at step (/app/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/app/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/app/node_modules/@ethersproject/web/lib/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","id":56,"error":{"code":-32000,"message":"invalid transaction v, r, s values"}}\n',
  error: Error: invalid transaction v, r, s values
      at getResult (/app/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:142:28)
      at processJsonFunc (/app/node_modules/@ethersproject/web/src.ts/index.ts:377:22)
      at /app/node_modules/@ethersproject/web/src.ts/index.ts:314:42
      at step (/app/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/app/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/app/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: -32000,
    data: undefined
  },
  requestBody: '{"method":"eth_sendRawTransaction","params":["0xf86d80843b9aca008252089473e56be4eba6e314522f6d3458353abb3c936b1f881bc16d674ec800008082099ca0ef68433d7974e759456725dc8f582fdd022780a398752150cbba8164ae85fac7a069dc3fd4c2fb59e1db043451e34e40b0c3a57a9e0c2f892856b3de851d770cb9"],"id":56,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'http://fixturenet-eth-geth-1:8545',
  transaction: {
    nonce: 0,
    gasPrice: BigNumber { _hex: '0x3b9aca00', _isBigNumber: true },
    gasLimit: BigNumber { _hex: '0x5208', _isBigNumber: true },
    to: '0x73E56bE4eBA6e314522f6D3458353abb3c936B1f',
    value: BigNumber { _hex: '0x1bc16d674ec80000', _isBigNumber: true },
    data: '0x',
    chainId: 1212,
    v: 2460,
    r: '0xef68433d7974e759456725dc8f582fdd022780a398752150cbba8164ae85fac7',
    s: '0x69dc3fd4c2fb59e1db043451e34e40b0c3a57a9e0c2f892856b3de851d770cb9',
    from: '0xe6CE22afe802CAf5fF7d3845cec8c736ecc8d61F',
    hash: '0x4120d8f6305ac47877e917d3b427792c39e1a6f6eddb2570dd1241d1e1f521ff',
    type: null,
    confirmations: 0
  },
  transactionHash: '0x4120d8f6305ac47877e917d3b427792c39e1a6f6eddb2570dd1241d1e1f521ff'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
wait-for-it.sh: waiting 60 seconds for fixturenet-eth-geth-1:8545
wait-for-it.sh: fixturenet-eth-geth-1:8545 is available after 0 seconds
Using L1 RPC endpoint http://fixturenet-eth-geth-1:8545
yarn run v1.22.19
$ /app/node_modules/.bin/hardhat rekey-json --output /l2-accounts/keys.json
L2 account keys written to /l2-accounts/keys.json
Done in 9.15s.
Fetching L1 account credentials using provided URL
--2023-07-20 04:11:16--  http://fixturenet-eth-bootnode-geth:9898/accounts.csv
Resolving fixturenet-eth-bootnode-geth (fixturenet-eth-bootnode-geth)... 192.168.176.3
Connecting to fixturenet-eth-bootnode-geth (fixturenet-eth-bootnode-geth)|192.168.176.3|:9898... connected.
HTTP request sent, awaiting response... 200 OK
Length: 762 [text/csv]
Saving to: '/geth-accounts/accounts.csv'

     0K                                                       100% 17.9M=0s

2023-07-20 04:11:16 (17.9 MB/s) - '/geth-accounts/accounts.csv' saved [762/762]

yarn run v1.22.19
$ /app/node_modules/.bin/hardhat send-balance --to 0xb554922a9deca1f6e00fbf980ce7c63af6df0bef --amount 2 --private-key 0x888814df89c4358d7ddb3fa4b0213e7331239a80e1f013eaa7b2deca2a41a218 --network getting-started
Balance sent to: 0xb554922a9deca1f6e00fbf980ce7c63af6df0bef, from: 0xe6CE22afe802CAf5fF7d3845cec8c736ecc8d61F
Block: { number: 6, hash: 0xd605eee853c09c649d8ab0edb37fef8b27bcebcda2fb6f636a5dee3e51894db0 }
Transaction hash: 0x36f4265a639889e958ac46c32b00b70ca824a27e1731cc685e8c28b73e8513f6
Done in 13.72s.
yarn run v1.22.19
$ /app/node_modules/.bin/hardhat send-balance --to 0x062b214aa82c517850ef3d6e9dcc033f5a47fdfb --amount 5 --private-key 0x888814df89c4358d7ddb3fa4b0213e7331239a80e1f013eaa7b2deca2a41a218 --network getting-started
Balance sent to: 0x062b214aa82c517850ef3d6e9dcc033f5a47fdfb, from: 0xe6CE22afe802CAf5fF7d3845cec8c736ecc8d61F
Block: { number: 12, hash: 0x20365f623f1d1222c7a05dd584321e3381b3c4de7bef89f33753d04d91b7f4c5 }
Transaction hash: 0x6ab53c83cf9de639f132b971354098fd8902a3ee14005b9b5ce30066a6ef1471
Done in 17.20s.
yarn run v1.22.19
$ /app/node_modules/.bin/hardhat send-balance --to 0x3fe654fb01985bc245588c3512d50d00ee558a07 --amount 1000 --private-key 0x888814df89c4358d7ddb3fa4b0213e7331239a80e1f013eaa7b2deca2a41a218 --network getting-started
Balance sent to: 0x3fe654fb01985bc245588c3512d50d00ee558a07, from: 0xe6CE22afe802CAf5fF7d3845cec8c736ecc8d61F
Block: { number: 16, hash: 0x19c07285abbe77a843e88aa035e0135006a538de95da61f369906559f698d079 }
Transaction hash: 0xad218683f13225ee86bc570ec53d3ae6eb2f508683a19ca386666e649ac48b09
Done in 12.86s.
Balances sent to L2 accounts
Error:
(code: -32603, message: method handler crashed, data: None)
Waiting for a finalized L1 block to exist, retrying after 10s
Error:
(code: -32603, message: method handler crashed, data: None)
Waiting for a finalized L1 block to exist, retrying after 10s
Error:
(code: -32603, message: method handler crashed, data: None)
Waiting for a finalized L1 block to exist, retrying after 10s
Error:
(code: -32603, message: method handler crashed, data: None)
Waiting for a finalized L1 block to exist, retrying after 10s
Error:
(code: -32603, message: method handler crashed, data: None)
Waiting for a finalized L1 block to exist, retrying after 10s
Error:
(code: -32603, message: method handler crashed, data: None)
Waiting for a finalized L1 block to exist, retrying after 10s
```

**Comment by dboreham** [comment]
Turned out it takes 10min to start.
