### ISSUE TITLE
mainnet-eth-plugeth stack won't start

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#599]
Something broken with ports:

```
$ laconic-so deployment --dir mainnet-eth-plugeth-deployment start
1 error(s) decoding:

* error decoding 'ports': Invalid containerPort: None
Traceback (most recent call last):
  File "/home/david/projects/stack-orchestrator/venv/bin/laconic-so", line 33, in <module>
    sys.exit(load_entry_point('laconic-stack-orchestrator', 'console_scripts', 'laconic-so')())
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/david/projects/stack-orchestrator/app/deployment.py", line 86, in start
    up_operation(ctx, services_list, stay_attached)
  File "/home/david/projects/stack-orchestrator/app/deploy.py", line 77, in up_operation
    deploy_context.docker.compose.up(detach=not stay_attached, services=services_list)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/python_on_whales/components/compose/cli_wrapper.py", line 749, in up
    run(full_cmd, capture_stdout=quiet, capture_stderr=quiet)
  File "/home/david/projects/stack-orchestrator/venv/lib/python3.10/site-packages/python_on_whales/utils.py", line 194, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker compose --file mainnet-eth-plugeth-deployment/compose/docker-compose-mainnet-eth-plugeth.yml --file mainnet-eth-plugeth-deployment/compose/docker-compose-mainnet-eth-ipld-eth-db.yml --file mainnet-eth-plugeth-deployment/compose/docker-compose-mainnet-eth-ipld-eth-server.yml --file mainnet-eth-plugeth-deployment/compose/docker-compose-mainnet-eth-keycloak.yml --file mainnet-eth-plugeth-deployment/compose/docker-compose-mainnet-eth-metrics.yml --env-file mainnet-eth-plugeth-deployment/config.env --project-name laconic-0d8d43cb8cf6708e6e39a7b57cf3e520 up --detach`.
It returned with code 15
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr can be found above the stacktrace (it wasn't captured).
```

**Comment by dboreham** [comment]
```
$ grep -R None mainnet-eth-plugeth-deployment
mainnet-eth-plugeth-deployment/mainnet-eth-plugeth-spec.yml:   - 0.0.0.0:None:None
mainnet-eth-plugeth-deployment/compose/docker-compose-mainnet-eth-ipld-eth-db.yml:     - 0.0.0.0:None:None
```

**Comment by dboreham** [comment]
Seems to be to do with this: https://github.com/cerc-io/stack-orchestrator/blob/telackey/pgmn/app/data/compose/docker-compose-mainnet-eth-ipld-eth-db.yml#L28C8-L28C8

**Comment by dboreham** [comment]
Fixed in the branch (bug doesn't seem to be on main).
