### ISSUE TITLE
Docker execute fails after k8s refactor

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#602]
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./package/laconic-so-1.1.0-c51671f-202310242051/__main__.py", line 3, in <module>
  File "./package/laconic-so-1.1.0-c51671f-202310242051/_bootstrap/__init__.py", line 253, in bootstrap
  File "./package/laconic-so-1.1.0-c51671f-202310242051/_bootstrap/__init__.py", line 38, in run
  File "/root/.shiv/laconic-so-1.1.0-c51671f-202310242051_1355863562ef846558c652369a50bc1ffc9e246b151ae94e5ee6432b7003bb3d/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/.shiv/laconic-so-1.1.0-c51671f-202310242051_1355863562ef846558c652369a50bc1ffc9e246b151ae94e5ee6432b7003bb3d/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/.shiv/laconic-so-1.1.0-c51671f-202310242051_1355863562ef846558c652369a50bc1ffc9e246b151ae94e5ee6432b7003bb3d/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.shiv/laconic-so-1.1.0-c51671f-202310242051_1355863562ef846558c652369a50bc1ffc9e246b151ae94e5ee6432b7003bb3d/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.shiv/laconic-so-1.1.0-c51671f-202310242051_1355863562ef846558c652369a50bc1ffc9e246b151ae94e5ee6432b7003bb3d/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.shiv/laconic-so-1.1.0-c51671f-202310242051_1355863562ef846558c652369a50bc1ffc9e246b151ae94e5ee6432b7003bb3d/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/.shiv/laconic-so-1.1.0-c51671f-202310242051_1355863562ef846558c652369a50bc1ffc9e246b151ae94e5ee6432b7003bb3d/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.shiv/laconic-so-1.1.0-c51671f-202310242051_1355863562ef846558c652369a50bc1ffc9e246b151ae94e5ee6432b7003bb3d/site-packages/app/deploy.py", line 205, in exec
    exec_operation(ctx, extra_args)
  File "/root/.shiv/laconic-so-1.1.0-c51671f-202310242051_1355863562ef846558c652369a50bc1ffc9e246b151ae94e5ee6432b7003bb3d/site-packages/app/deploy.py", line 154, in exec_operation
    ctx.obj.deployer.compose_execute(service_name, command_to_exec, envs=container_exec_env)
  File "/root/.shiv/laconic-so-1.1.0-c51671f-202310242051_1355863562ef846558c652369a50bc1ffc9e246b151ae94e5ee6432b7003bb3d/site-packages/app/deploy_docker.py", line 53, in compose_execute
    return self.docker.compose.execute(service_name=service_name, command=command, envs=envs)
TypeError: execute() got an unexpected keyword argument 'service_name'
```

**Comment by dboreham** [comment]
Fixed in: https://github.com/cerc-io/stack-orchestrator/pull/603
