### ISSUE TITLE
deploy-system ps fails on fixturenet-eth

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#61]
```
$ laconic-so deploy-system --include fixturenet-eth ps
Running containers:
id: 98a215001f1fad616069596228610d27f97d11e6c28ccf628a699db50087278e, name: laconic-3074009f3e3e79146218c78fffd19a0a-fixturenet-eth-bootnode-geth-1, ports: 0.0.0.0:54506->30303/tcp,Traceback (most recent call last):
  File "/home/david/projects/cerc/stack-orchestrator/venv/bin/laconic-so", line 33, in <module>
    sys.exit(load_entry_point('laconic-stack-orchestrator', 'console_scripts', 'laconic-so')())
  File "/home/david/projects/cerc/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/projects/cerc/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/david/projects/cerc/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david/projects/cerc/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/projects/cerc/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/david/projects/cerc/stack-orchestrator/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/david/projects/cerc/stack-orchestrator/app/deploy_system.py", line 96, in command
    print(f"{ports[port_mapping][0]['HostIp']}:{ports[port_mapping][0]['HostPort']}->{port_mapping}", end=",")
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dboreham** [comment]
Problem is to do with handling container ports that are not mapped into the host network.

**Comment by dboreham** [comment]
Fixed in: https://github.com/cerc-io/stack-orchestrator/pull/88
