### ISSUE TITLE
fixturenet-payments stack doesn't build

### ISSUE THREAD

**Issue by zramsay** [cerc-io/stack-orchestrator#617]
specifically, `ipld-eth-server` fails with:

```
Step 10/27 : RUN if [ -n "$GIT_VDBTO_TOKEN" ]; then git config --global url."https://$GIT_VDBTO_TOKEN:@git.vdb.to/".insteadOf "https://git.vdb.to/"; fi &&     go mod download &&     rm -f ~/.gitconfig
 ---> Running in 3521ffbea166
verifying git.vdb.to/cerc-io/eth-iterator-utils@v0.1.2: checksum mismatch
	downloaded: h1:+3+T+J21J/VkhlCFujl8HT4XuwebavIuKj0+qfE+0QM=
	go.sum:     h1:PdMR5B9wrQSYuYpFhN+9Kc8AEZ0pTt5eKCmu8oCtFcY=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
The command '/bin/sh -c if [ -n "$GIT_VDBTO_TOKEN" ]; then git config --global url."https://$GIT_VDBTO_TOKEN:@git.vdb.to/".insteadOf "https://git.vdb.to/"; fi &&     go mod download &&     rm -f ~/.gitconfig' returned a non-zero code: 1
Error running build for cerc/ipld-eth-server
FATAL Error: container build failed and --continue-on-error not set, exiting
```

**Comment by zramsay** [comment]
```
laconic-so --stack fixturenet-payments build-containers --force-rebuild --exclude cerc/ipld-eth-server
laconic-so --stack fixturenet-payments deploy --cluster payments up
```

error:
```
✔ Container payments-fixturenet-eth-lighthouse-2-1         Started                                                                   0.0s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
Traceback (most recent call last):
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/deploy/compose/deploy_docker.py", line 29, in up
    return self.docker.compose.up(detach=detach, services=services)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/python_on_whales/components/compose/cli_wrapper.py", line 749, in up
    run(full_cmd, capture_stdout=quiet, capture_stderr=quiet)
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/python_on_whales/utils.py", line 194, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker compose --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-fixturenet-eth.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-ipld-eth-server-payments.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-ipld-eth-db.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-nitro-contracts.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-go-nitro.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-nitro-rpc-client.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-watcher-mobymask-v3.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-mobymask-snap.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-mobymask-app-v3.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-ponder-indexer.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-ponder-watcher.yml --project-name payments up --detach`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr can be found above the stacktrace (it wasn't captured).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/bin/laconic-so/__main__.py", line 3, in <module>
  File "/root/bin/laconic-so/_bootstrap/__init__.py", line 253, in bootstrap
  File "/root/bin/laconic-so/_bootstrap/__init__.py", line 38, in run
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/deploy/deploy.py", line 176, in up
    up_operation(ctx, extra_args_list)
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/deploy/deploy.py", line 83, in up_operation
    deploy_context.deployer.up(detach=not stay_attached, services=services_list)
  File "/root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/deploy/compose/deploy_docker.py", line 31, in up
    raise DeployerException(e)
app.deploy.deployer.DeployerException: The docker command executed was `/usr/bin/docker compose --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-fixturenet-eth.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-ipld-eth-server-payments.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-ipld-eth-db.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-nitro-contracts.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-go-nitro.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-nitro-rpc-client.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-watcher-mobymask-v3.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-mobymask-snap.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-mobymask-app-v3.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-ponder-indexer.yml --file /root/.shiv/laconic-so_2eae478682c5cbe80f18d34f8d02a6d1c845ab94db42187f823b4ffc260b4d10/site-packages/app/data/compose/docker-compose-ponder-watcher.yml --project-name payments up --detach`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr can be found above the stacktrace (it wasn't captured).
```
