### ISSUE TITLE
`eth-probe-db` unhealthy container

### ISSUE THREAD

**Issue by zramsay** [cerc-io/stack-orchestrator#75]
I've encountered this error a few times while playing around. Not currrently a blocker.

```
container for service "eth-probe-db" is unhealthy
Traceback (most recent call last):
  File "/root/stack-orchestrator/venv/bin/laconic-so", line 33, in <module>
    sys.exit(load_entry_point('laconic-stack-orchestrator', 'console_scripts', 'laconic-so')())
  File "/root/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/stack-orchestrator/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/stack-orchestrator/app/deploy_system.py", line 81, in command
    docker.compose.up(detach=True, services=services_list)
  File "/root/stack-orchestrator/venv/lib/python3.10/site-packages/python_on_whales/components/compose/cli_wrapper.py", line 723, in up
    run(full_cmd, capture_stdout=quiet, capture_stderr=quiet)
  File "/root/stack-orchestrator/venv/lib/python3.10/site-packages/python_on_whales/utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/bin/docker compose --file compose/docker-compose-db.yml --file compose/docker-compose-ipld-eth-beacon-db.yml --file compose/docker-compose-ipld-eth-beacon-indexer.yml --file compose/docker-compose-ipld-eth-server.yml --file compose/docker-compose-fixturenet-eth.yml --file compose/docker-compose-eth-probe.yml --file compose/docker-compose-keycloak.yml --project-name laconic-52db386ed2ca20c21c0d12f8e8e81af4 up --detach`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
```

**Comment by dboreham** [comment]
Can you post the laconic-so command you ran please?

**Comment by telackey** [comment]
`eth-probe-db` is just a timescale instance, so pretty much the only things that can go wrong are running out of resources or some problem loading the schema (expected to be located at `../eth-probe/db/schema.sql`)

**Comment by dboreham** [comment]
Also post any `docker logs` output please.

**Comment by zramsay** [comment]
```
(venv) Zachs-Air:stack-orchestrator stars$ docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
(venv) Zachs-Air:stack-orchestrator stars$ laconic-so deploy-system --include db,fixturenet-eth,ipld-eth-server,ipld-eth-beacon-db,ipld-eth-beacon-indexer,eth-probe,keycloak up
WARN[0000] The "eth_forward_eth_calls" variable is not set. Defaulting to a blank string. 
WARN[0000] The "eth_proxy_on_error" variable is not set. Defaulting to a blank string. 
WARN[0000] The "eth_http_path" variable is not set. Defaulting to a blank string. 
[+] Running 17/18
 ⠿ Network laconic-515b4020f964b70ab3826351cd3f9eb5_default                                 Created                                               0.1s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-ipld-eth-db-1                         Healthy                                              65.4s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-ipld-eth-beacon-db-1                  Healthy                                              69.8s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-bootnode-lighthouse-1  Started                                               3.4s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-bootnode-geth-1        Started                                               4.0s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-keycloak-db-1                         Healthy                                              35.0s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-eth-probe-db-1                        Waiting                                             100.7s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-keycloak-1                            Started                                              36.1s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-geth-1-1               Healthy                                              67.7s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-geth-2-1               Healthy                                              96.9s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-eth-probe-mq-1                        Created                                               0.3s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-migrations-1                          Started                                              67.1s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-ipld-eth-server-1                     Started                                              67.2s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-lighthouse-1-1         Healthy                                              99.1s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-lighthouse-2-1         Started                                              98.0s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-eth-probe-probe-1                     Created                                               0.3s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-keycloak-nginx-1                      Started                                              37.5s
 ⠿ Container laconic-515b4020f964b70ab3826351cd3f9eb5-ipld-eth-beacon-indexer-1             Started                                              99.7s
container for service "eth-probe-db" is unhealthy
Traceback (most recent call last):
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/venv/bin/laconic-so", line 33, in <module>
    sys.exit(load_entry_point('laconic-stack-orchestrator', 'console_scripts', 'laconic-so')())
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/app/deploy_system.py", line 81, in command
    docker.compose.up(detach=True, services=services_list)
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/venv/lib/python3.10/site-packages/python_on_whales/components/compose/cli_wrapper.py", line 723, in up
    run(full_cmd, capture_stdout=quiet, capture_stderr=quiet)
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/venv/lib/python3.10/site-packages/python_on_whales/utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/local/bin/docker compose --file compose/docker-compose-db.yml --file compose/docker-compose-ipld-eth-beacon-db.yml --file compose/docker-compose-ipld-eth-beacon-indexer.yml --file compose/docker-compose-ipld-eth-server.yml --file compose/docker-compose-fixturenet-eth.yml --file compose/docker-compose-eth-probe.yml --file compose/docker-compose-keycloak.yml --project-name laconic-515b4020f964b70ab3826351cd3f9eb5 up --detach`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr can be found above the stacktrace (it wasn't captured).
(venv) Zachs-Air:stack-orchestrator stars$ docker ps -a | ack eth-probe
1cbe52574696   cerc/eth-probe:local                   "/app/run.sh"            2 minutes ago   Created                                                                                                     laconic-515b4020f964b70ab3826351cd3f9eb5-eth-probe-probe-1
310454aa3ad4   cerc/eth-probe:local                   "/app/run.sh"            2 minutes ago   Created                                                                                                     laconic-515b4020f964b70ab3826351cd3f9eb5-eth-probe-mq-1
fa06e207fe88   timescale/timescaledb:latest-pg14      "docker-entrypoint.s…"   2 minutes ago   Up About a minute (healthy)   0.0.0.0:56159->5432/tcp                                                       laconic-515b4020f964b70ab3826351cd3f9eb5-eth-probe-db-1
(venv) Zachs-Air:stack-orchestrator stars$ docker logs 1cbe52574696
(venv) Zachs-Air:stack-orchestrator stars$ docker logs 310454aa3ad4

**Comment by zramsay** [comment]
maybe relevant but I noticed there's some other duplicate containers:

```
(venv) Zachs-Air:stack-orchestrator stars$ docker ps -a
CONTAINER ID   IMAGE                                  COMMAND                  CREATED         STATUS                             PORTS                                                                         NAMES
064779baaf62   cerc/ipld-eth-beacon-indexer:local     "./entrypoint.sh"        2 minutes ago   Up 23 seconds                                                                                                    laconic-515b4020f964b70ab3826351cd3f9eb5-ipld-eth-beacon-indexer-1
1181801a5d73   nginx:1.23-alpine                      "/docker-entrypoint.…"   2 minutes ago   Up About a minute                  0.0.0.0:56158->80/tcp                                                         laconic-515b4020f964b70ab3826351cd3f9eb5-keycloak-nginx-1
1cbe52574696   cerc/eth-probe:local                   "/app/run.sh"            2 minutes ago   Created                                                                                                          laconic-515b4020f964b70ab3826351cd3f9eb5-eth-probe-probe-1
c6c8b751efc8   cerc/fixturenet-eth-lighthouse:local   "/opt/testnet/run.sh"    2 minutes ago   Up 25 seconds (health: starting)                                                                                 laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-lighthouse-2-1
6e2c73ef95ce   cerc/fixturenet-eth-lighthouse:local   "/opt/testnet/run.sh"    2 minutes ago   Up 54 seconds (healthy)            0.0.0.0:56240->8001/tcp                                                       laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-lighthouse-1-1
2323504dff79   cerc/ipld-eth-server:local             "/app/entrypoint.sh"     2 minutes ago   Up 56 seconds (healthy)            127.0.0.1:8081-8082->8081-8082/tcp                                            laconic-515b4020f964b70ab3826351cd3f9eb5-ipld-eth-server-1
a4a54d136731   cerc/ipld-eth-db:local                 "/app/startup_script…"   2 minutes ago   Up 56 seconds                                                                                                    laconic-515b4020f964b70ab3826351cd3f9eb5-migrations-1
935a8a5865f7   cerc/fixturenet-eth-geth:local         "/opt/testnet/run.sh"    2 minutes ago   Up About a minute (healthy)        8545-8546/tcp, 30303/tcp, 30303/udp                                           laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-geth-2-1
310454aa3ad4   cerc/eth-probe:local                   "/app/run.sh"            2 minutes ago   Created                                                                                                          laconic-515b4020f964b70ab3826351cd3f9eb5-eth-probe-mq-1
651f7fb32ca8   cerc/keycloak:local                    "/opt/keycloak/bin/k…"   2 minutes ago   Up About a minute                  8443/tcp, 0.0.0.0:56148->8080/tcp                                             laconic-515b4020f964b70ab3826351cd3f9eb5-keycloak-1
393249a5cfea   cerc/fixturenet-eth-geth:local         "/opt/testnet/run.sh"    2 minutes ago   Up About a minute (healthy)        8546/tcp, 30303/tcp, 30303/udp, 0.0.0.0:56063->8545/tcp                       laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-geth-1-1
0f623f83c075   postgres:14-alpine                     "docker-entrypoint.s…"   2 minutes ago   Up About a minute (healthy)        0.0.0.0:56054->5432/tcp                                                       laconic-515b4020f964b70ab3826351cd3f9eb5-keycloak-db-1
aca8916e3dd5   cerc/fixturenet-eth-geth:local         "/opt/testnet/run.sh"    2 minutes ago   Up About a minute                  8545-8546/tcp, 30303/udp, 0.0.0.0:56055->9898/tcp, 0.0.0.0:56056->30303/tcp   laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-bootnode-geth-1
fa06e207fe88   timescale/timescaledb:latest-pg14      "docker-entrypoint.s…"   2 minutes ago   Up About a minute (healthy)        0.0.0.0:56159->5432/tcp                                                       laconic-515b4020f964b70ab3826351cd3f9eb5-eth-probe-db-1
71ac63ec89c6   timescale/timescaledb:2.8.1-pg14       "docker-entrypoint.s…"   2 minutes ago   Up About a minute (healthy)        127.0.0.1:8077->5432/tcp                                                      laconic-515b4020f964b70ab3826351cd3f9eb5-ipld-eth-db-1
f7a2675cf40a   cerc/fixturenet-eth-lighthouse:local   "/opt/testnet/run.sh"    2 minutes ago   Up 2 minutes                                                                                                     laconic-515b4020f964b70ab3826351cd3f9eb5-fixturenet-eth-bootnode-lighthouse-1
c63668060510   cerc/ipld-eth-beacon-db:local          "docker-entrypoint.s…"   2 minutes ago   Up About a minute (healthy)        127.0.0.1:8076->5432/tcp                                                      laconic-515b4020f964b70ab3826351cd3f9eb5-ipld-eth-beacon-db-1
```

**Comment by dboreham** [comment]
Docker is a bit annoying in this area. There are some tricks to shed light on what it is up to.

I'd try the following:

1. in another window see if you can get any `docker logs` output from the bad container _before_ compose aborts the startup process and kills it.
2. Use the docker-fu here to see what the container's healthcheck is doing: https://stackoverflow.com/a/42738182/1701505

You might also try starting just that container. Append `eth-probe-db` to the `deploy-system ... up` command, like `...deploy-system ... up eth-probe-db`. iirc that will only start that one container and will therefore make it easier to see the signal from noise.

**Comment by zramsay** [comment]
this issue had disappeared until today but with a different container:
```
container for service "fixturenet-eth-geth-2" is unhealthy
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/./laconic-so/__main__.py", line 3, in <module>
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/./laconic-so/_bootstrap/__init__.py", line 253, in bootstrap
  File "/Users/stars/go/src/github.com/cerc-io/stack-orchestrator/./laconic-so/_bootstrap/__init__.py", line 38, in run
  File "/Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/app/deploy_system.py", line 87, in command
    docker.compose.up(detach=True, services=services_list)
  File "/Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/python_on_whales/components/compose/cli_wrapper.py", line 723, in up
    run(full_cmd, capture_stdout=quiet, capture_stderr=quiet)
  File "/Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/python_on_whales/utils.py", line 177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `/usr/local/bin/docker compose --file /Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/app/data/compose/docker-compose-ipld-eth-db.yml --file /Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/app/data/compose/docker-compose-ipld-eth-server.yml --file /Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/app/data/compose/docker-compose-fixturenet-laconicd.yml --file /Users/stars/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/app/data/compose/docker-compose-fixturenet-eth.yml --project-name laconic-9f9e2accf70415390f25d1fffb387476 up --detach`.
It returned with code 1
The content of stdout can be found above the stacktrace (it wasn't captured).
```

**Comment by zramsay** [comment]
my gut was telling me that this happens when `deploy-system` isn't using the latest available or is missing smth, so re-running `setup-repos` and `build-containers` did solve the problem

**Comment by dboreham** [comment]
I wonder if this was a case of the healthcheck being too quick on a heavily loaded machine?
Has it happened recently?

**Comment by zramsay** [comment]
This is a plausible explanation. Subjectively, it did seem to happen more often when a machine is heavily loaded. Haven't run into it recently

**Comment by dboreham** [comment]
Closing since this hasn't reappeared recently. We probably need to do a pass over all our container healthchecks to get them in good shape.
