### ISSUE TITLE
`laconic-so deploy-system ps` fails

### ISSUE THREAD

**Issue by telackey** [cerc-io/stack-orchestrator#78]
I suspect this is related to containers with more than on exposed port, but I have not confirmed.

```
./laconic-so deploy-system ps
Running containers:
id: 9deeadfcc67789047adbe56b8ccb2ae59b4949fef21dbc9d0b9c7b2aec885c14, name: laconic-5b7409b167310a18c83d930ac1d342f3-eth-probe-db-1, ports: 0.0.0.0:55849->5432/tcp,
id: 748688b99693bd8a77f8cf7dc0b7aa6d79afbc5a50ce2fff706e506703a3518e, name: laconic-5b7409b167310a18c83d930ac1d342f3-eth-probe-mq-1, ports:
id: ed28ed6612cd4cacb8b84119b382a835a0edd8664df33ac9a17953810ddd3343, name: laconic-5b7409b167310a18c83d930ac1d342f3-eth-probe-probe-1, ports:
id: 2404f3108a927b4ad4bada07f56a8000dcb031dc9dcb767cab239edd8a4874b7, name: laconic-5b7409b167310a18c83d930ac1d342f3-fixturenet-eth-bootnode-geth-1, ports: 0.0.0.0:55848->30303/tcp,Traceback (most recent call last):
  File "/Users/telackey/Documents/BPI/cerc/stack-orchestrator/./laconic-so", line 33, in <module>
    sys.exit(load_entry_point('laconic-stack-orchestrator', 'console_scripts', 'laconic-so')())
  File "/Users/telackey/Documents/BPI/cerc/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/telackey/Documents/BPI/cerc/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/telackey/Documents/BPI/cerc/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/telackey/Documents/BPI/cerc/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/telackey/Documents/BPI/cerc/stack-orchestrator/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/telackey/Documents/BPI/cerc/stack-orchestrator/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/telackey/Documents/BPI/cerc/stack-orchestrator/app/deploy_system.py", line 96, in command
    print(f"{ports[port_mapping][0]['HostIp']}:{ports[port_mapping][0]['HostPort']}->{port_mapping}", end=",")
TypeError: 'NoneType' object is not subscriptable
```

**Comment by telackey** [comment]
Duplicate of https://github.com/cerc-io/stack-orchestrator/issues/61
